# Generated by Django 3.2.12 on 2022-04-03 13:46

from django.db import migrations, models
import django.db.models.deletion
import namegen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('a2_code', namegen.models.ActualCharField(max_length=2)),
                ('a3_code', namegen.models.ActualCharField(max_length=3)),
                ('un_code', namegen.models.ActualCharField(max_length=3)),
                ('has_names', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NamesDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField()),
                ('given_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='namegen.country')),
            ],
        ),
    ]
