# Generated by Django 3.2.12 on 2022-04-05 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('namegen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255, null=True)),
                ('downloaded_by', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expired_at', models.DateTimeField()),
                ('age', models.IntegerField(default=1)),
            ],
        ),
    ]
